CREATE WAREHOUSE INTERVIEW_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE;
CREATE DATABASE USER_NIKHIL COMMENT = 'Database for ph Data Assignment';
CREATE SCHEMA "USER_NIKHIL"."DB_SF_INGESTION";